### Exercici 4

Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".

cuando las dos matrices coinciden en todas sus dimensiones , las operaciones son compatibles entre ellas :

In [17]:
import numpy as np
a=np.array([[2,2,2,],[3,3,3,]])
print("Matriz a:")
print(a)
print("con la forma "+str(a.shape))
b=np.array([[4,4,4],[4,4,4]])
print("Matriz b:")
print(b)
print("con la forma "+str(b.shape))
print()
print("Sumamos las matrices a y b")
c=a+b
print("Obtenemos la matriz: ")
print(c)
print("manteniendo la forma "+str(c.shape))


Matriz a:
[[2 2 2]
 [3 3 3]]
con la forma (2, 3)
Matriz b:
[[4 4 4]
 [4 4 4]]
con la forma (2, 3)

Sumamos las matrices a y b
Obtenemos la matriz: 
[[6 6 6]
 [7 7 7]]
con la forma (2, 3)


tambien son compatibles cuando coinciden parcialmente sus dimensiones , empezando por la izquierda, que sería como si nos inventaremos una dimension extra de valor 1

In [15]:
import numpy as np
a=np.array([[2,2,2,],[3,3,3,]])
print("Matriz a:")
print(a)

print("con la forma "+str(a.shape))
b=np.array([[[3,3,3,],[4,4,4]],[[3,3,3,],[4,4,4]],[[3,3,3,],[4,4,4]]])
print("Matriz b:")
print(b)
print("con la forma "+str(b.shape))
print()
print("Sumamos las matrices a y b")
c=a+b
print("Obtenemos la matriz: ")
print(c)
print("con la forma "+str(c.shape))





Matriz a:
[[2 2 2]
 [3 3 3]]
con la forma (2, 3)
Matriz b:
con la forma (3, 2, 3)
Sumamos las matrices a y b
Obtenemos la matriz: 
[[[5 5 5]
  [7 7 7]]

 [[5 5 5]
  [7 7 7]]

 [[5 5 5]
  [7 7 7]]]
con la forma (3, 2, 3)


es como si numpy redefiniese la matriz a de la siguiente forma y aplicase la regla de la dimesión, como se muestras en el siguiente código.

In [ ]:
import numpy as np
a=np.array([[[2,2,2,],[3,3,3,]]])
print(a.shape)

si las 2 matrices coinciden en todas las dimensiones excepto una , y en esta dimension una de las 2 matrices es de dimension 1 . Las matrices son compatibles , ya que se "expande" la dimensión 1 de la matriz para hacer compatible las operaciones:

In [14]:
import numpy as np
a=np.array([[2,2,2],[3,3,3]])
print("Tomamos 2 matrices, matriz a")
print(a)
print("Con forma "+str(a.shape))
b=np.array([[2,2,2]])
print("y la matriz b")
print(b)
print("con forma "+str(b.shape))
print("Expandimos la dimensión de la matriz b , hasta hacerlo compatible con a y poder sumarlas")
c=a+b
print("Obtenemos la matriz:")     
print(c)
print("con forma "+str(c.shape))
print("es como definir b de la siguiente manera:")
b=np.array([[2,2,2],[2,2,2]])
print(b.shape)
c=a+b
print(c)


Tomamos 2 matrices, matriz a
[[2 2 2]
 [3 3 3]]
Con forma (2, 3)
y la matriz b
[[2 2 2]]
con forma (1, 3)
Expandimos la dimensión de la matriz b , hasta hacerlo compatible con a y poder sumarlas
Obtenemos la matriz:
[[4 4 4]
 [5 5 5]]
con forma (2, 3)
es como definir b de la siguiente manera:
(2, 3)
[[4 4 4]
 [5 5 5]]


### Exercici 5
Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [8]:
import numpy as np
a=np.array([[4,4,4,4],[3,3,3,3],[1,2,3,8]])

print("Matriz ejemplo")
print(a)
print()
print("mostramos la primera columna")
print(a[:,0])#el 0 marca la columna
print("ahora la suma de los elementos de la primera columna")
print(np.add.reduce(a[:,0]))
print()
print("mostramos la primera fila")
print(a[(0)])
print("y la suma de sus elementos")
print(np.add.reduce(a[(0)]))


Matriz ejemplo
[[4 4 4 4]
 [3 3 3 3]
 [1 2 3 8]]

mostramos la primera columna
[4 3 1]
ahora la suma de los elementos de la primera columna
8

mostramos la primera fila
[4 4 4 4]
y la suma de sus elementos
16


### Exercici 6
Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.
Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.

In [10]:
import numpy as np
mascara=np.where(a%4==0,True,False)
print("obtenemos la matriz mascara:")
print()
print(mascara)

obtenemos la matriz mascara:
[[ True  True  True  True]
 [False False False False]
 [False False False  True]]


### Exercici 7
A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.

In [6]:
#usar l amatriz true/false para sacar los valores que se dividen por 4 
import numpy as np

#mostrar divisibles entre 4
mostrar_filtrado=a[mascara]
print("Valores de la matriz divisibles entre 4: " +str(mostrar_filtrado))


Valores de la matriz divisibles entre 4[4 4 4 4 8]
