
### Nivell 1


- Exercici 1

Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. .


In [1]:
import numpy as np
num_enteros=np.array([12,123,342342,234,23432,1,2,312,31246,8988,7778769,4365456,45633])
print(num_enteros)
print("Shape : "+str(num_enteros.shape))
print("Dimension: "+str(num_enteros.ndim))


[     12     123  342342     234   23432       1       2     312   31246
    8988 7778769 4365456   45633]
Shape : (13,)
Dimension: 1


- Exercici 2

De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

- Primera solución : modo programador

In [2]:

def valor_medio(array_1d):
    suma=0
    for num in array_1d:
        suma+=num
    media=suma/len(num_enteros)
    return (media)
               
print("El valor medio es "+str(valor_medio(num_enteros)))     
print("El resto en apartado siguiente :)")


El valor medio es 968965.3846153846
El resto en apartado siguiente :)


- Segunda solución:modo DataScience

In [3]:
import numpy as np
mediana= round(np.median(num_enteros),2)
print("La mediana es "+ str(mediana))
media_val= round(np.mean(num_enteros),2)
print("El valor medio es "+str(media_val))
print("Diferencia: "+ str(media_val-mediana))

La mediana es 8988.0
El valor medio es 968965.38
Diferencia: 959977.38


- Exercici 3

Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.


In [4]:
import numpy as np
matriz=np.array([[3,5,34,5,6],[8,43,7,4,3],[1,6,3,8,45],[3,4,23,4,1],[6,4,1,6,34]])
print("Shape: "+str(matriz.shape))
print("Dimensión: "+str(matriz.ndim))

Shape: (5, 5)
Dimensión: 2


- modo programador

In [5]:
#modo programador
maximo=matriz[0,0]
for x in matriz:
    for y in x:
        if (y>maximo):
            maximo=y
print("Máximo de la matriz : "+str(maximo))
print("El resto en modo DAtaScience ;)")

Máximo de la matriz : 45
El resto en modo DAtaScience ;)


- modo DataScience

In [6]:
#otra()
print("Máximo de la matriz : "+str(matriz.max()))

Máximo de la matriz : 45


In [7]:
#max dimensión
print("matriz")
print(matriz)
print()
maximos_x=matriz.max(axis=0)
maximos_y=matriz.max(axis=1)
print("Máximos en columnas"+str(maximos_x))
print("Máximos en filas " +str(maximos_y))

matriz
[[ 3  5 34  5  6]
 [ 8 43  7  4  3]
 [ 1  6  3  8 45]
 [ 3  4 23  4  1]
 [ 6  4  1  6 34]]

Máximos en columnas[ 8 43 34  8 45]
Máximos en filas [34 43 45 23 34]


- modo programador

In [8]:

maximo_filas=[]

for x in matriz:
    maximo_filas.append(x.max())
        
print("Máximos de las filas : "+str(maximo_filas))


Máximos de las filas : [34, 43, 45, 23, 34]
